version: "3.8"

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # [추가] 초기 DB 세팅을 위해 init.sql 파일을 컨테이너 내부에 연결합니다.
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: fastapi_web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
