CREATE TABLE PLACES (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    image_url VARCHAR(255) NOT NULL
);

CREATE TABLE RESTAURANTS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    location VARCHAR(100) NOT NULL,
    latitude DECIMAL(10,8) NOT NULL,
    longitude DECIMAL(11,8) NOT NULL,
    image_url VARCHAR(255),
    corkage_info VARCHAR(255)
);

CREATE TABLE TAGS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE RESTAURANT_TAGS (
    restaurant_id INT REFERENCES RESTAURANTS(id),
    tag_id INT REFERENCES TAGS(id),
    PRIMARY KEY (restaurant_id, tag_id)
);

CREATE TABLE NON_ALCOHOL_OPTIONS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE RESTAURANT_NON_ALCOHOLS (
    restaurant_id INT REFERENCES RESTAURANTS(id),
    option_id INT REFERENCES NON_ALCOHOL_OPTIONS(id),
    PRIMARY KEY (restaurant_id, option_id)
);

CREATE TABLE USERS (
    id SERIAL PRIMARY KEY,
    nickname VARCHAR(50)
);

CREATE TABLE RECENT_SEARCHES (
    id SERIAL PRIMARY KEY,
    user_id INT REFERENCES USERS(id),
    keyword VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE FAVORITE_RESTAURANTS (
    user_id INT REFERENCES USERS(id),
    restaurant_id INT REFERENCES RESTAURANTS(id),
    PRIMARY KEY (user_id, restaurant_id)
);
